In [1]:
import pandas as pd

In [2]:
micromamba list

List of packages in environment: "/home/sithy/micromamba/envs/datascience"

  Name                           Version       Build                 Channel
──────────────────────────────────────────────────────────────────────────────────
  _openmp_mutex                  4.5           20_gnu                conda-forge
  _python_abi3_support           1.0           hd8ed1ab_2            conda-forge
  alsa-lib                       1.2.16.1      hb03c661_0            conda-forge
  anyio                          4.14.0        pyhcf101f3_0          conda-forge
  argon2-cffi                    25.1.0        pyhd8ed1ab_0          conda-forge
  argon2-cffi-bindings           25.1.0        py312h4c3975b_2       conda-forge
  arrow                          1.4.0         pyhcf101f3_0          conda-forge
  asttokens                      3.0.1         pyhd8ed1ab_0          conda-forge
  async-lru                      2.3.0         pyhcf101f3_0          conda-forge
  attrs                          26.1.0        pyhcf101f3_0          conda-forge
  babel                          2.18.0        pyhcf101f3_1          conda-forge
  backports.zstd                 1.6.0         py312h90b7ffd_0       conda-forge
  beautifulsoup4                 4.15.0        pyha770c72_0          conda-forge
  bleach                         6.4.0         pyhcf101f3_0          conda-forge
  bleach-with-css                6.4.0         hac0b51c_0            conda-forge
  brotli                         1.2.0         hed03a55_1            conda-forge
  brotli-bin                     1.2.0         hb03c661_1            conda-forge
  brotli-python                  1.2.0         py312hdb49522_1       conda-forge
  bzip2                          1.0.8         hda65f42_9            conda-forge
  ca-certificates                2026.6.17     hbd8a1cb_0            conda-forge
  cached-property                1.5.2         hd8ed1ab_1            conda-forge
  cached_property                1.5.2         pyha770c72_1          conda-forge
  cairo                          1.18.4        he90730b_1            conda-forge
  certifi                        2026.6.17     pyhd8ed1ab_0          conda-forge
  cffi                           2.0.0         py312h460c074_1       conda-forge
  charset-normalizer             3.4.7         pyhd8ed1ab_0          conda-forge
  comm                           0.2.3         pyhe01879c_0          conda-forge
  contourpy                      1.3.3         py312h0a2e395_4       conda-forge
  cpython                        3.12.13       py312hd8ed1ab_0       conda-forge
  cycler                         0.12.1        pyhcf101f3_2          conda-forge
  cyrus-sasl                     2.1.28        hac629b4_1            conda-forge
  dbus                           1.16.2        h24cb091_1            conda-forge
  debugpy                        1.8.21        py312h8285ef7_0       conda-forge
  decorator                      5.3.1         pyhd8ed1ab_0          conda-forge
  defusedxml                     0.7.1         pyhd8ed1ab_0          conda-forge
  double-conversion              3.4.0         hecca717_0            conda-forge
  et_xmlfile                     2.0.0         pyhd8ed1ab_1          conda-forge
  exceptiongroup                 1.3.1         pyhd8ed1ab_0          conda-forge
  executing                      2.2.1         pyhd8ed1ab_0          conda-forge
  font-ttf-dejavu-sans-mono      2.37          hab24e00_0            conda-forge
  font-ttf-inconsolata           3.000         h77eed37_0            conda-forge
  font-ttf-source-code-pro       2.038         h77eed37_0            conda-forge
  font-ttf-ubuntu                0.83          h77eed37_3            conda-forge
  fontconfig                     2.18.1        h27c8c51_0            conda-forge
  fonts-conda-ecosystem          1             0                     conda-forge
  fonts-conda-forge              1             hc364b38_1            conda-forge
  fonttools                      4.63.0        py312h8a5da7c_0       conda-forge
  fqdn                           1.5.1         pyhd8ed1ab_1          conda-forge
  freetype                       2.14.3        ha770c72_0            conda-forge
  fribidi                        1.0.16        hb03c661_0            conda-forge
  graphite2                      1.3.15        hecca717_0            conda-forge
  h11                            0.16.0        pyhcf101f3_1          conda-forge
  h2                             4.3.0         pyhcf101f3_0          conda-forge
  harfbuzz                       14.2.1        h6083320_0            conda-forge
  hpack                          4.1.0         pyhd8ed1ab_0          conda-forge
  httpcore                       1.0.9         pyh29332c3_0          conda-forge
  httpx                          0.28.1        pyhd8ed1ab_0          conda-forge
  hyperframe                     6.1.0         pyhd8ed1ab_0          conda-forge
  icu                            78.3          h33c6efd_0            conda-forge
  idna                           3.18          pyhcf101f3_0          conda-forge
  importlib-metadata             9.0.0         pyhcf101f3_0          conda-forge
  ipykernel                      7.3.0         pyha191276_0          conda-forge
  ipython                        9.14.1        pyh53cf698_0          conda-forge
  ipython_pygments_lexers        1.1.1         pyhd8ed1ab_0          conda-forge
  isoduration                    20.11.0       pyhd8ed1ab_1          conda-forge
  jedi                           0.19.2        pyhd8ed1ab_1          conda-forge
  jinja2                         3.1.6         pyhcf101f3_1          conda-forge
  joblib                         1.5.3         pyhd8ed1ab_0          conda-forge
  json5                          0.14.0        pyhd8ed1ab_0          conda-forge
  jsonpointer                    3.1.1         pyhcf101f3_0          conda-forge
  jsonschema                     4.26.0        pyhcf101f3_0          conda-forge
  jsonschema-specifications      2025.9.1      pyhcf101f3_0          conda-forge
  jsonschema-with-format-nongpl  4.26.0        hcf101f3_0            conda-forge
  jupyter-builder                1.0.2         pyhcf101f3_0          conda-forge
  jupyter-lsp                    2.3.1         pyhcf101f3_0          conda-forge
  jupyter_client                 8.9.1         pyhcf101f3_0          conda-forge
  jupyter_core                   5.9.1         pyhc90fa1f_0          conda-forge
  jupyter_events                 0.12.1        pyhcf101f3_0          conda-forge
  jupyter_server                 2.20.0        pyhcf101f3_0          conda-forge
  jupyter_server_terminals       0.5.4         pyhcf101f3_0          conda-forge
  jupyterlab                     4.6.0         pyhd8ed1ab_0          conda-forge
  jupyterlab_pygments            0.3.0         pyhd8ed1ab_2          conda-forge
  jupyterlab_server              2.28.0        pyhcf101f3_0          conda-forge
  keyutils                       1.6.3         hb9d3cd8_0            conda-forge
  kiwisolver                     1.5.0         py312h0a2e395_0       conda-forge
  krb5                           1.22.2        ha1258a1_0            conda-forge
  lark                           1.3.1         pyhd8ed1ab_0          conda-forge
  lcms2                          2.19.1        h0c24ade_1            conda-forge
  ld_impl_linux-64               2.45.1        default_hbd61a6d_102  conda-forge
  lerc                           4.1.0         hdb68285_0            conda-forge
  libblas                        3.11.0        8_h4a7cf45_openblas   conda-forge
  libbrotlicommon                1.2.0         hb03c661_1            conda-forge
  libbrotlidec                   1.2.0         hb03c661_1            conda-forge
  libbrotlienc                   1.2.0         hb03c661_1            conda-forge
  libcblas                       3.11.0        8_h0358290_openblas   conda-forge
  libclang13                     22.1.8        default_h746c552_1    conda-forge
  libcups                        2.3.3         h7a8fb5f_6            conda-forge
  libdeflate                     1.25          h17f619e_0            conda-forge
  libdrm                         2.4.127       hb03c661_0            conda-forge
  libedit                        3.1.20250104  pl5321h7949ede_0      conda-forge
  libegl                         1.7.0         ha4b6fd6_3            conda-forge
  libegl-devel                   1.7.0         ha4b6fd6_3            conda-forge
  libexpat                       2.8.1         hecca717_1            conda-forge
  libffi                         3.5.2         h3435931_0            conda-forge
  libfreetype                    2.14.3        ha770c72_0            conda-forge
  libfreetype6                   2.14.3        h73754d4_0            conda-forge
  libgcc                         15.2.0        he0feb66_19           conda-forge
  libgcc-ng                      15.2.0        h69a702a_19           conda-forge
  libgfortran                    15.2.0        h69a702a_19           conda-forge
  libgfortran5                   15.2.0        h68bc16d_19           conda-forge
  libgl                          1.7.0         ha4b6fd6_3            conda-forge
  libgl-devel                    1.7.0         ha4b6fd6_3            conda-forge
  libglib                        2.88.1        h0d30a3d_2            conda-forge
  libglvnd                       1.7.0         ha4b6fd6_3            conda-forge
  libglx                         1.7.0         ha4b6fd6_3            conda-forge
  libglx-devel                   1.7.0         ha4b6fd6_3            conda-forge
  libgomp                        15.2.0        he0feb66_19           conda-forge
  libiconv                       1.18          h3b78370_2            conda-forge
  libjpeg-turbo                  3.1.4.1       hb03c661_0            conda-forge
  liblapack                      3.11.0        8_h47877c9_openblas   conda-forge
  libllvm22                      22.1.8        hf7376ad_1            conda-forge
  liblzma                        5.8.3         hb03c661_0            conda-forge
  libnsl                         2.0.1         hb9d3cd8_1            conda-forge
  libntlm                        1.8           hb9d3cd8_0            conda-forge
  libopenblas                    0.3.33        pthreads_h94d23a6_0   conda-forge
  libopengl                      1.7.0         ha4b6fd6_3            conda-forge
  libpciaccess                   0.19          hb03c661_0            conda-forge
  libpng                         1.6.58        h421ea60_0            conda-forge
  libpq                          18.4          hd5a49e9_0            conda-forge
  libraqm                        0.10.5        h75b3fb1_0            conda-forge
  libsodium                      1.0.22        h280c20c_1            conda-forge
  libsqlite                      3.53.2        h0c1763c_0            conda-forge
  libstdcxx                      15.2.0        h934c35e_19           conda-forge
  libstdcxx-ng                   15.2.0        hdf11a46_19           conda-forge
  libtiff                        4.7.1         h9d88235_1            conda-forge
  libuuid                        2.42.2        h5347b49_0            conda-forge
  libvulkan-loader               1.4.341.0     h5279c79_0            conda-forge
  libwebp-base                   1.6.0         hd42ef1d_0            conda-forge
  libxcb                         1.17.0        h8a09558_0            conda-forge
  libxcrypt                      4.4.36        hd590300_1            conda-forge
  libxkbcommon                   1.13.2        hca5e8e5_0            conda-forge
  libxml2                        2.15.3        h49c6c72_0            conda-forge
  libxml2-16                     2.15.3        hca6bf5a_0            conda-forge
  libxslt                        1.1.43        h711ed8c_1            conda-forge
  libzlib                        1.3.2         h25fd6f3_2            conda-forge
  markupsafe                     3.0.3         py312h8a5da7c_1       conda-forge
  matplotlib                     3.11.0        py312h7900ff3_0       conda-forge
  matplotlib-base                3.11.0        py312h1c5ec97_0       conda-forge
  matplotlib-inline              0.2.2         pyhd8ed1ab_0          conda-forge
  mistune                        3.2.1         pyhcf101f3_0          conda-forge
  munkres                        1.1.4         pyhd8ed1ab_1          conda-forge
  narwhals                       2.22.1        pyhcf101f3_0          conda-forge
  nbclient                       0.11.0        pyhd8ed1ab_0          conda-forge
  nbconvert-core                 7.17.1        pyhcf101f3_0          conda-forge
  nbformat                       5.10.4        pyhd8ed1ab_1          conda-forge
  ncurses                        6.6           hdb14827_0            conda-forge
  nest-asyncio2                  1.7.2         pyhcf101f3_0          conda-forge
  notebook-shim                  0.2.4         pyhd8ed1ab_1          conda-forge
  numpy                          2.4.6         py312h33ff503_0       conda-forge
  openjpeg                       2.5.4         h55fea9a_0            conda-forge
  openldap                       2.6.13        hbde042b_0            conda-forge
  openpyxl                       3.1.5         py312h7f6eeab_3       conda-forge
  openssl                        3.6.3         h35e630c_0            conda-forge
  overrides                      7.7.0         pyhd8ed1ab_1          conda-forge
  packaging                      26.2          pyhc364b38_0          conda-forge
  pandas                         3.0.3         py312h8ecdadd_0       conda-forge
  pandocfilters                  1.5.0         pyhd8ed1ab_0          conda-forge
  parso                          0.8.7         pyhcf101f3_0          conda-forge
  patsy                          1.0.2         pyhcf101f3_0          conda-forge
  pcre2                          10.47         haa7fec5_0            conda-forge
  pexpect                        4.9.0         pyhd8ed1ab_1          conda-forge
  pillow                         12.2.0        py312h50c33e8_0       conda-forge
  pip                            26.1.2        pyh8b19718_0          conda-forge
  pixman                         0.46.4        h54a6638_1            conda-forge
  platformdirs                   4.10.0        pyhcf101f3_0          conda-forge
  plotly                         6.8.0         pyhd8ed1ab_0          conda-forge
  prometheus_client              0.25.0        pyhd8ed1ab_0          conda-forge
  prompt-toolkit                 3.0.52        pyha770c72_0          conda-forge
  psutil                         7.2.2         py312h5253ce2_0       conda-forge
  pthread-stubs                  0.4           hb9d3cd8_1002         conda-forge
  ptyprocess                     0.7.0         pyhd8ed1ab_1          conda-forge
  pure_eval                      0.2.3         pyhd8ed1ab_1          conda-forge
  pycparser                      3.0           pyhcf101f3_0          conda-forge
  pygments                       2.20.0        pyhd8ed1ab_0          conda-forge
  pyparsing                      3.3.2         pyhcf101f3_0          conda-forge
  pyside6                        6.11.1        py312h50ac2ff_1       conda-forge
  pysocks                        1.7.1         pyha55dd90_7          conda-forge
  python                         3.12.13       hd63d673_0_cpython    conda-forge
  python-dateutil                2.9.0.post0   pyhe01879c_2          conda-forge
  python-fastjsonschema          2.21.2        pyhe01879c_0          conda-forge
  python-gil                     3.12.13       hd8ed1ab_0            conda-forge
  python-json-logger             4.1.0         pyhd8ed1ab_0          conda-forge
  python-tzdata                  2026.2        pyhd8ed1ab_0          conda-forge
  python_abi                     3.12          8_cp312               conda-forge
  pyyaml                         6.0.3         py312h8a5da7c_1       conda-forge
  pyzmq                          27.1.0        py312hda471dd_3       conda-forge
  qhull                          2020.2        h434a139_5            conda-forge
  qt6-main                       6.11.1        pl5321h16c4a6b_1      conda-forge
  readline                       8.3           h853b02a_0            conda-forge
  referencing                    0.37.0        pyhcf101f3_0          conda-forge
  requests                       2.34.2        pyhcf101f3_0          conda-forge
  rfc3339-validator              0.1.4         pyhd8ed1ab_1          conda-forge
  rfc3986-validator              0.1.1         pyh9f0ad1d_0          conda-forge
  rfc3987-syntax                 1.1.0         pyhe01879c_1          conda-forge
  rpds-py                        2026.5.1      py312h192e038_0       conda-forge
  scikit-learn                   1.9.0         np2py312h3226591_0    conda-forge
  scipy                          1.17.1        py312h54fa4ab_1       conda-forge
  seaborn                        0.13.2        hd8ed1ab_3            conda-forge
  seaborn-base                   0.13.2        pyhd8ed1ab_3          conda-forge
  send2trash                     2.1.0         pyha191276_1          conda-forge
  setuptools                     82.0.1        pyh332efcf_0          conda-forge
  six                            1.17.0        pyhe01879c_1          conda-forge
  sniffio                        1.3.1         pyhd8ed1ab_2          conda-forge
  soupsieve                      2.8.4         pyhd8ed1ab_0          conda-forge
  stack_data                     0.6.3         pyhd8ed1ab_1          conda-forge
  statsmodels                    0.14.6        py312h4f23490_0       conda-forge
  terminado                      0.18.1        pyhc90fa1f_1          conda-forge
  threadpoolctl                  3.6.0         pyhecae5ae_0          conda-forge
  tinycss2                       1.4.0         pyhd8ed1ab_0          conda-forge
  tk                             8.6.13        noxft_h366c992_103    conda-forge
  tomli                          2.4.1         pyhcf101f3_0          conda-forge
  tornado                        6.5.7         py312h4c3975b_0       conda-forge
  traitlets                      5.15.1        pyhcf101f3_0          conda-forge
  typing-extensions              4.15.0        h396c80c_0            conda-forge
  typing_extensions              4.15.0        pyhcf101f3_0          conda-forge
  typing_utils                   0.1.0         pyhd8ed1ab_1          conda-forge
  tzdata                         2025c         hc9c84f9_1            conda-forge
  unicodedata2                   17.0.1        py312h4c3975b_0       conda-forge
  uri-template                   1.3.0         pyhd8ed1ab_1          conda-forge
  urllib3                        2.7.0         pyhd8ed1ab_0          conda-forge
  wayland                        1.25.0        hd6090a7_0            conda-forge
  wcwidth                        0.8.1         pyhd8ed1ab_0          conda-forge
  webcolors                      25.10.0       pyhd8ed1ab_0          conda-forge
  webencodings                   0.5.1         pyhd8ed1ab_3          conda-forge
  websocket-client               1.9.0         pyhd8ed1ab_0          conda-forge
  wheel                          0.47.0        pyhd8ed1ab_0          conda-forge
  xcb-util                       0.4.1         h4f16b4b_2            conda-forge
  xcb-util-cursor                0.1.6         hb03c661_0            conda-forge
  xcb-util-image                 0.4.0         hb711507_2            conda-forge
  xcb-util-keysyms               0.4.1         hb711507_0            conda-forge
  xcb-util-renderutil            0.3.10        hb711507_0            conda-forge
  xcb-util-wm                    0.4.2         hb711507_0            conda-forge
  xkeyboard-config               2.47          h280c20c_1            conda-forge
  xorg-libice                    1.1.2         hb9d3cd8_0            conda-forge

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('/home/sithy/Coding/Data Science/Datasets/ai_student_impact_dataset.csv')

In [3]:
data.head()

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
0,100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.393,86.44,High
1,100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
2,100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium
3,100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
4,100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium

In [4]:
data.describe()

,Student_ID,Pre_Semester_GPA,Weekly_GenAI_Hours,Tool_Diversity,Traditional_Study_Hours,Perceived_AI_Dependency,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score
count,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,125000.500000,3.146102,8.427752,2.80026,11.209271,3.505360,4.270760,3.349299,75.798125
std,14433.901067,0.478854,8.269490,1.18802,5.156426,1.820812,2.144066,0.495673,13.281626
min,100001.000000,1.183000,0.000000,1.00000,1.000000,1.000000,1.000000,1.000000,10.780000
25%,112500.750000,2.834000,2.390000,2.00000,7.560000,2.000000,3.000000,3.023750,66.820000
50%,125000.500000,3.210000,5.800000,3.00000,11.180000,3.000000,4.000000,3.421000,76.000000
75%,137500.250000,3.521000,11.720000,4.00000,14.710000,5.000000,6.000000,3.749000,85.190000
max,150000.000000,3.998000,40.000000,5.00000,35.860000,10.000000,10.000000,4.000000,100.000000

In [ ]:
data.isnull().sum()

Student_ID                    0
Major_Category                0
Year_of_Study                 0
Pre_Semester_GPA              0
Weekly_GenAI_Hours            0
Primary_Use_Case              0
Prompt_Engineering_Skill      0
Tool_Diversity                0
Paid_Subscription             0
Traditional_Study_Hours       0
Perceived_AI_Dependency       0
Institutional_Policy          0
Anxiety_Level_During_Exams    0
Post_Semester_GPA             0
Skill_Retention_Score         0
Burnout_Risk_Level            0
dtype: int64

In [7]:
data.columns

Index(['Student_ID', 'Major_Category', 'Year_of_Study', 'Pre_Semester_GPA',
       'Weekly_GenAI_Hours', 'Primary_Use_Case', 'Prompt_Engineering_Skill',
       'Tool_Diversity', 'Paid_Subscription', 'Traditional_Study_Hours',
       'Perceived_AI_Dependency', 'Institutional_Policy',
       'Anxiety_Level_During_Exams', 'Post_Semester_GPA',
       'Skill_Retention_Score', 'Burnout_Risk_Level'],
      dtype='str')

In [13]:
data.nunique()

Student_ID                    50000
Major_Category                    5
Year_of_Study                     5
Pre_Semester_GPA               2389
Weekly_GenAI_Hours             3566
Primary_Use_Case                  5
Prompt_Engineering_Skill          3
Tool_Diversity                    5
Paid_Subscription                 2
Traditional_Study_Hours        2516
Perceived_AI_Dependency          10
Institutional_Policy              3
Anxiety_Level_During_Exams       10
Post_Semester_GPA              2269
Skill_Retention_Score          5872
Burnout_Risk_Level                3
dtype: int64

In [14]:
conda list

/usr/bin/bash: line 1: conda: command not found

Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('/home/sithy/Coding/Data Science/Datasets/Social_media_impact_on_life.csv')

In [4]:
df.shape

(4500, 16)

In [5]:
df.columns

Index(['Student_ID', 'Age', 'Gender', 'Academic_Level', 'Primary_Platform',
       'Daily_Usage_Hours', 'Weekend_Extra_Hours', 'Device_Type',
       'Sleep_Duration_Hours', 'Sleep_Quality_Score', 'Late_Night_Usage',
       'Social_Comparison_Frequency', 'Perceived_Stress_Score',
       'Mental_Health_Index', 'Academic_Performance_GPA', 'Overall_Impact'],
      dtype='str')

In [6]:
df

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
0,STU_2024000,19,Female,Undergraduate,Snapchat,7.5,1.5,Smartphone,5.9,2,True,Always,20.0,73,2.73,Neutral
1,STU_2024001,19,Female,Undergraduate,Instagram,4.6,1.3,Smartphone,7.9,3,True,Sometimes,17.0,90,3.21,Beneficial
2,STU_2024002,17,Female,High School,TikTok,10.9,1.7,Smartphone,5.2,1,True,Frequently,18.0,70,3.00,Neutral
3,STU_2024003,16,Female,High School,YouTube,6.0,2.3,Tablet,7.6,4,True,Sometimes,15.0,82,3.42,Beneficial
4,STU_2024004,17,Male,High School,LinkedIn,3.3,2.6,Smartphone,7.6,4,True,Never,16.0,84,3.41,Beneficial
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,STU_2028495,16,Male,High School,YouTube,5.8,1.2,Smartphone,7.8,3,True,Sometimes,11.0,79,2.85,Beneficial
4496,STU_2028496,19,Female,Undergraduate,LinkedIn,3.8,3.0,Smartphone,6.6,3,False,Frequently,9.0,83,3.37,Beneficial
4497,STU_2028497,19,Male,Undergraduate,Instagram,7.7,1.1,Smartphone,6.0,2,True,Frequently,13.0,73,3.16,Beneficial
4498,STU_2028498,16,Male,High School,LinkedIn,4.6,3.3,Laptop/PC,7.1,3,False,Sometimes,22.0,87,3.50,Beneficial
4499,STU_2028499,24,Male,Undergraduate,Instagram,1.8,2.1,Smartphone,6.8,3,True,Frequently,10.0,98,3.73,Beneficial

In [8]:
df.describe()

,Age,Daily_Usage_Hours,Weekend_Extra_Hours,Sleep_Duration_Hours,Sleep_Quality_Score,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA
count,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000,4454.000000,4500.000000,4415.000000
mean,18.703333,5.295933,1.796844,6.701333,2.472000,13.512124,79.873111,3.429282
std,1.981182,2.604497,0.699245,1.189998,1.030484,7.072859,12.876044,0.392662
min,15.000000,0.900000,0.000000,3.000000,1.000000,0.000000,32.000000,1.900000
25%,17.000000,3.400000,1.300000,6.000000,2.000000,9.000000,72.000000,3.200000
50%,19.000000,4.700000,1.800000,6.800000,3.000000,13.000000,82.000000,3.460000
75%,20.000000,6.600000,2.300000,7.500000,3.000000,18.000000,89.000000,3.720000
max,26.000000,14.000000,4.500000,10.500000,5.000000,40.000000,98.000000,4.000000

In [11]:
df.columns

Index(['Student_ID', 'Age', 'Gender', 'Academic_Level', 'Primary_Platform',
       'Daily_Usage_Hours', 'Weekend_Extra_Hours', 'Device_Type',
       'Sleep_Duration_Hours', 'Sleep_Quality_Score', 'Late_Night_Usage',
       'Social_Comparison_Frequency', 'Perceived_Stress_Score',
       'Mental_Health_Index', 'Academic_Performance_GPA', 'Overall_Impact'],
      dtype='str')

In [15]:
df_clean = df.dropna(subset=['Academic_Performance_GPA', 'Perceived_Stress_Score'], axis=0)

In [16]:
df_clean

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
0,STU_2024000,19,Female,Undergraduate,Snapchat,7.5,1.5,Smartphone,5.9,2,True,Always,20.0,73,2.73,Neutral
1,STU_2024001,19,Female,Undergraduate,Instagram,4.6,1.3,Smartphone,7.9,3,True,Sometimes,17.0,90,3.21,Beneficial
2,STU_2024002,17,Female,High School,TikTok,10.9,1.7,Smartphone,5.2,1,True,Frequently,18.0,70,3.00,Neutral
3,STU_2024003,16,Female,High School,YouTube,6.0,2.3,Tablet,7.6,4,True,Sometimes,15.0,82,3.42,Beneficial
4,STU_2024004,17,Male,High School,LinkedIn,3.3,2.6,Smartphone,7.6,4,True,Never,16.0,84,3.41,Beneficial
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,STU_2028495,16,Male,High School,YouTube,5.8,1.2,Smartphone,7.8,3,True,Sometimes,11.0,79,2.85,Beneficial
4496,STU_2028496,19,Female,Undergraduate,LinkedIn,3.8,3.0,Smartphone,6.6,3,False,Frequently,9.0,83,3.37,Beneficial
4497,STU_2028497,19,Male,Undergraduate,Instagram,7.7,1.1,Smartphone,6.0,2,True,Frequently,13.0,73,3.16,Beneficial
4498,STU_2028498,16,Male,High School,LinkedIn,4.6,3.3,Laptop/PC,7.1,3,False,Sometimes,22.0,87,3.50,Beneficial
4499,STU_2028499,24,Male,Undergraduate,Instagram,1.8,2.1,Smartphone,6.8,3,True,Frequently,10.0,98,3.73,Beneficial

In [17]:
df_clean.describe()

,Age,Daily_Usage_Hours,Weekend_Extra_Hours,Sleep_Duration_Hours,Sleep_Quality_Score,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA
count,4369.000000,4369.000000,4369.000000,4369.000000,4369.000000,4369.000000,4369.000000,4369.000000
mean,18.703136,5.302014,1.796384,6.698901,2.471046,13.529183,79.817578,3.429680
std,1.980096,2.608300,0.697976,1.188141,1.028952,7.068291,12.872718,0.392935
min,15.000000,0.900000,0.000000,3.000000,1.000000,0.000000,32.000000,1.900000
25%,17.000000,3.400000,1.300000,6.000000,2.000000,9.000000,72.000000,3.200000
50%,19.000000,4.700000,1.800000,6.800000,3.000000,13.000000,82.000000,3.470000
75%,20.000000,6.600000,2.300000,7.500000,3.000000,18.000000,89.000000,3.720000
max,26.000000,14.000000,4.500000,10.500000,5.000000,40.000000,98.000000,4.000000

In [2]:
df.columns

NameError: name 'df' is not defined

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('/home/sithy/Coding/Data Science/Datasets/Social_media_impact_on_life.csv')

In [5]:
df_clean

NameError: name 'df_clean' is not defined

In [6]:
df

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
0,STU_2024000,19,Female,Undergraduate,Snapchat,7.5,1.5,Smartphone,5.9,2,True,Always,20.0,73,2.73,Neutral
1,STU_2024001,19,Female,Undergraduate,Instagram,4.6,1.3,Smartphone,7.9,3,True,Sometimes,17.0,90,3.21,Beneficial
2,STU_2024002,17,Female,High School,TikTok,10.9,1.7,Smartphone,5.2,1,True,Frequently,18.0,70,3.00,Neutral
3,STU_2024003,16,Female,High School,YouTube,6.0,2.3,Tablet,7.6,4,True,Sometimes,15.0,82,3.42,Beneficial
4,STU_2024004,17,Male,High School,LinkedIn,3.3,2.6,Smartphone,7.6,4,True,Never,16.0,84,3.41,Beneficial
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,STU_2028495,16,Male,High School,YouTube,5.8,1.2,Smartphone,7.8,3,True,Sometimes,11.0,79,2.85,Beneficial
4496,STU_2028496,19,Female,Undergraduate,LinkedIn,3.8,3.0,Smartphone,6.6,3,False,Frequently,9.0,83,3.37,Beneficial
4497,STU_2028497,19,Male,Undergraduate,Instagram,7.7,1.1,Smartphone,6.0,2,True,Frequently,13.0,73,3.16,Beneficial
4498,STU_2028498,16,Male,High School,LinkedIn,4.6,3.3,Laptop/PC,7.1,3,False,Sometimes,22.0,87,3.50,Beneficial
4499,STU_2028499,24,Male,Undergraduate,Instagram,1.8,2.1,Smartphone,6.8,3,True,Frequently,10.0,98,3.73,Beneficial

In [7]:
df.describe

<bound method NDFrame.describe of        Student_ID  Age  Gender Academic_Level Primary_Platform  \
0     STU_2024000   19  Female  Undergraduate         Snapchat
1     STU_2024001   19  Female  Undergraduate        Instagram
2     STU_2024002   17  Female    High School           TikTok
3     STU_2024003   16  Female    High School          YouTube
4     STU_2024004   17    Male    High School         LinkedIn
...           ...  ...     ...            ...              ...
4495  STU_2028495   16    Male    High School          YouTube
4496  STU_2028496   19  Female  Undergraduate         LinkedIn
4497  STU_2028497   19    Male  Undergraduate        Instagram
4498  STU_2028498   16    Male    High School         LinkedIn
4499  STU_2028499   24    Male  Undergraduate        Instagram

      Daily_Usage_Hours  Weekend_Extra_Hours Device_Type  \
0                   7.5                  1.5  Smartphone
1                   4.6                  1.3  Smartphone
2                  10.9                  1.7  Smartphone
3                   6.0                  2.3      Tablet
4                   3.3                  2.6  Smartphone
...                 ...                  ...         ...
4495                5.8                  1.2  Smartphone
4496                3.8                  3.0  Smartphone
4497                7.7                  1.1  Smartphone
4498                4.6                  3.3   Laptop/PC
4499                1.8                  2.1  Smartphone

      Sleep_Duration_Hours  Sleep_Quality_Score  Late_Night_Usage  \
0                      5.9                    2              True
1                      7.9                    3              True
2                      5.2                    1              True
3                      7.6                    4              True
4                      7.6                    4              True
...                    ...                  ...               ...
4495                   7.8                    3              True
4496                   6.6                    3             False
4497                   6.0                    2              True
4498                   7.1                    3             False
4499                   6.8                    3              True

     Social_Comparison_Frequency  Perceived_Stress_Score  Mental_Health_Index  \
0                         Always                    20.0                   73
1                      Sometimes                    17.0                   90
2                     Frequently                    18.0                   70
3                      Sometimes                    15.0                   82
4                          Never                    16.0                   84
...                          ...                     ...                  ...
4495                   Sometimes                    11.0                   79
4496                  Frequently                     9.0                   83
4497                  Frequently                    13.0                   73
4498                   Sometimes                    22.0                   87
4499                  Frequently                    10.0                   98

      Academic_Performance_GPA Overall_Impact
0                         2.73        Neutral
1                         3.21     Beneficial
2                         3.00        Neutral
3                         3.42     Beneficial
4                         3.41     Beneficial
...                        ...            ...
4495                      2.85     Beneficial
4496                      3.37     Beneficial
4497                      3.16     Beneficial
4498                      3.50     Beneficial
4499                      3.73     Beneficial

[4500 rows x 16 columns]>

In [8]:
df.describe()

,Age,Daily_Usage_Hours,Weekend_Extra_Hours,Sleep_Duration_Hours,Sleep_Quality_Score,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA
count,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000,4454.000000,4500.000000,4415.000000
mean,18.703333,5.295933,1.796844,6.701333,2.472000,13.512124,79.873111,3.429282
std,1.981182,2.604497,0.699245,1.189998,1.030484,7.072859,12.876044,0.392662
min,15.000000,0.900000,0.000000,3.000000,1.000000,0.000000,32.000000,1.900000
25%,17.000000,3.400000,1.300000,6.000000,2.000000,9.000000,72.000000,3.200000
50%,19.000000,4.700000,1.800000,6.800000,3.000000,13.000000,82.000000,3.460000
75%,20.000000,6.600000,2.300000,7.500000,3.000000,18.000000,89.000000,3.720000
max,26.000000,14.000000,4.500000,10.500000,5.000000,40.000000,98.000000,4.000000

In [9]:
df.columns

Index(['Student_ID', 'Age', 'Gender', 'Academic_Level', 'Primary_Platform',
       'Daily_Usage_Hours', 'Weekend_Extra_Hours', 'Device_Type',
       'Sleep_Duration_Hours', 'Sleep_Quality_Score', 'Late_Night_Usage',
       'Social_Comparison_Frequency', 'Perceived_Stress_Score',
       'Mental_Health_Index', 'Academic_Performance_GPA', 'Overall_Impact'],
      dtype='str')